"""add expression tasks

Revision ID: 8ffe8217e389
Revises: 033cef4e2369
Create Date: 2025-12-22 13:11:26.435036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffe8217e389'
down_revision = '033cef4e2369'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###