"""initial database schema - all models

Revision ID: 910b5fc6b6fa
Revises: 
Create Date: 2025-12-19 17:28:32.564287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '910b5fc6b6fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('TRAINING_CENTER', 'RESELLER', name='organizationtype', native_enum=False, length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_type'), ['type'], unique=False)

    op.create_table('plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('B2C', 'B2B_RESELLER', 'B2B_CENTER', name='plantype', native_enum=False, length=50), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ai_credits', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_type'), ['type'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('PLATFORM_ADMIN', 'ORG_ADMIN', 'TEACHER', 'STUDENT', name='userrole', native_enum=False, length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CORRECTION_READY', 'CREDITS_LOW', 'EXPIRATION_WARNING', 'NEW_STUDENT', 'PAYMENT_SUCCESS', name='notificationtype', native_enum=False, length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('organization_admins',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    op.create_table('organization_subscriptions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('slots_type', sa.Enum('FIXED', 'CONCURRENT', name='slotstype', native_enum=False, length=50), nullable=False),
    sa.Column('ai_credits_total', sa.Integer(), nullable=False),
    sa.Column('ai_credits_remaining', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_subscriptions_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_subscriptions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_subscriptions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_subscriptions_start_date'), ['start_date'], unique=False)

    op.create_table('organization_teachers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    op.create_table('series',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_number'), ['number'], unique=True)

    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ai_credits_remaining', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('comprehension_questions',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ORAL', 'WRITTEN', name='questiontype', native_enum=False, length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Enum('A', 'B', 'C', 'D', name='correctanswer', native_enum=False, length=10), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comprehension_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comprehension_questions_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprehension_questions_type'), ['type'], unique=False)

    op.create_table('exam_attempts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='attemptstatus', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_attempts_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_attempts_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_attempts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('expression_tasks',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('WRITTEN', 'ORAL', name='tasktype', native_enum=False, length=50), nullable=False),
    sa.Column('instruction_text', sa.Text(), nullable=False),
    sa.Column('instruction_audio_url', sa.String(length=500), nullable=True),
    sa.Column('word_count_min', sa.Integer(), nullable=True),
    sa.Column('word_count_max', sa.Integer(), nullable=True),
    sa.Column('preparation_time_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_time_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expression_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expression_tasks_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expression_tasks_type'), ['type'], unique=False)

    op.create_table('payments',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('org_subscription_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('MOBILE_MONEY', 'CARD', 'BANK_TRANSFER', name='paymentmethod', native_enum=False, length=50), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='paymentstatus', native_enum=False, length=50), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_subscription_id'], ['organization_subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_reference')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('student_aggregated_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('best_oral_score', sa.Integer(), nullable=True),
    sa.Column('best_written_score', sa.Integer(), nullable=True),
    sa.Column('avg_oral_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_written_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('first_attempt_date', sa.Date(), nullable=True),
    sa.Column('last_attempt_date', sa.Date(), nullable=True),
    sa.Column('progression_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_aggregated_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_aggregated_stats_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_aggregated_stats_user_id'), ['user_id'], unique=False)

    op.create_table('comprehension_answers',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_answer', sa.Enum('A', 'B', 'C', 'D', name='selectedanswer', native_enum=False, length=10), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['comprehension_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comprehension_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comprehension_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprehension_answers_question_id'), ['question_id'], unique=False)

    op.create_table('comprehension_results',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('ORAL', 'WRITTEN', name='questiontype', native_enum=False, length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comprehension_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comprehension_results_attempt_id'), ['attempt_id'], unique=False)

    op.create_table('oral_expressions',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('file_size_mb', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correction_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['expression_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oral_expressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oral_expressions_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oral_expressions_correction_status'), ['correction_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_oral_expressions_delete_at'), ['delete_at'], unique=False)

    op.create_table('written_expressions',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correction_status', sa.Enum('PENDING', 'CORRECTED_AI', 'CORRECTED_MANUAL', name='correctionstatus', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['expression_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('written_expressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_written_expressions_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_written_expressions_correction_status'), ['correction_status'], unique=False)

    op.create_table('oral_expression_corrections',
    sa.Column('expression_id', sa.UUID(), nullable=False),
    sa.Column('corrector_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expression_id'], ['oral_expressions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oral_expression_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oral_expression_corrections_expression_id'), ['expression_id'], unique=True)

    op.create_table('written_expression_ai_corrections',
    sa.Column('expression_id', sa.UUID(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=False),
    sa.Column('linguistic_score', sa.Integer(), nullable=True),
    sa.Column('linguistic_feedback', sa.Text(), nullable=True),
    sa.Column('pragmatic_score', sa.Integer(), nullable=True),
    sa.Column('pragmatic_feedback', sa.Text(), nullable=True),
    sa.Column('sociolinguistic_score', sa.Integer(), nullable=True),
    sa.Column('sociolinguistic_feedback', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('cecrl_level', sa.String(length=10), nullable=True),
    sa.Column('appreciation', sa.Text(), nullable=True),
    sa.Column('corrections_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggestions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_cost_tokens', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expression_id'], ['written_expressions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('written_expression_ai_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_written_expression_ai_corrections_expression_id'), ['expression_id'], unique=True)

    op.create_table('written_expression_manual_corrections',
    sa.Column('expression_id', sa.UUID(), nullable=False),
    sa.Column('corrector_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expression_id'], ['written_expressions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('written_expression_manual_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_written_expression_manual_corrections_expression_id'), ['expression_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('written_expression_manual_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_written_expression_manual_corrections_expression_id'))

    op.drop_table('written_expression_manual_corrections')
    with op.batch_alter_table('written_expression_ai_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_written_expression_ai_corrections_expression_id'))

    op.drop_table('written_expression_ai_corrections')
    with op.batch_alter_table('oral_expression_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oral_expression_corrections_expression_id'))

    op.drop_table('oral_expression_corrections')
    with op.batch_alter_table('written_expressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_written_expressions_correction_status'))
        batch_op.drop_index(batch_op.f('ix_written_expressions_attempt_id'))

    op.drop_table('written_expressions')
    with op.batch_alter_table('oral_expressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oral_expressions_delete_at'))
        batch_op.drop_index(batch_op.f('ix_oral_expressions_correction_status'))
        batch_op.drop_index(batch_op.f('ix_oral_expressions_attempt_id'))

    op.drop_table('oral_expressions')
    with op.batch_alter_table('comprehension_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comprehension_results_attempt_id'))

    op.drop_table('comprehension_results')
    with op.batch_alter_table('comprehension_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comprehension_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_comprehension_answers_attempt_id'))

    op.drop_table('comprehension_answers')
    with op.batch_alter_table('student_aggregated_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_aggregated_stats_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_aggregated_stats_subscription_id'))

    op.drop_table('student_aggregated_stats')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_status'))
        batch_op.drop_index(batch_op.f('ix_payments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_number'))

    op.drop_table('payments')
    with op.batch_alter_table('expression_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expression_tasks_type'))
        batch_op.drop_index(batch_op.f('ix_expression_tasks_series_id'))

    op.drop_table('expression_tasks')
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_attempts_status'))
        batch_op.drop_index(batch_op.f('ix_exam_attempts_started_at'))
        batch_op.drop_index(batch_op.f('ix_exam_attempts_series_id'))

    op.drop_table('exam_attempts')
    with op.batch_alter_table('comprehension_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comprehension_questions_type'))
        batch_op.drop_index(batch_op.f('ix_comprehension_questions_series_id'))

    op.drop_table('comprehension_questions')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_start_date'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_is_active'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_end_date'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_number'))
        batch_op.drop_index(batch_op.f('ix_series_is_active'))

    op.drop_table('series')
    op.drop_table('organization_teachers')
    with op.batch_alter_table('organization_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_subscriptions_start_date'))
        batch_op.drop_index(batch_op.f('ix_organization_subscriptions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_subscriptions_is_active'))
        batch_op.drop_index(batch_op.f('ix_organization_subscriptions_end_date'))

    op.drop_table('organization_subscriptions')
    op.drop_table('organization_admins')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_type'))
        batch_op.drop_index(batch_op.f('ix_plans_name'))
        batch_op.drop_index(batch_op.f('ix_plans_is_active'))

    op.drop_table('plans')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_type'))
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_is_active'))

    op.drop_table('organizations')
    # ### end Alembic commands ###