"""make plan_id nullable and add custom fields to subscriptions

Revision ID: 81ca93297f68
Revises: 910b5fc6b6fa
Create Date: 2025-12-21 06:21:41.519806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ca93297f68'
down_revision = '910b5fc6b6fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_duration_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('custom_ai_credits', sa.Integer(), nullable=True))
        batch_op.alter_column('plan_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('plan_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('custom_ai_credits')
        batch_op.drop_column('custom_duration_days')

    # ### end Alembic commands ###