"""update ai correction fields for TCF Canada official criteria

Revision ID: 90debe1792d3
Revises: 8ffe8217e389
Create Date: 2025-12-31 03:01:55.073035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90debe1792d3'
down_revision = '8ffe8217e389'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('written_expression_ai_corrections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structure_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('structure_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cohesion_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cohesion_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vocabulary_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vocabulary_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('grammar_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grammar_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('task_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('task_feedback', sa.Text(), nullable=True))
        batch_op.drop_column('linguistic_score')
        batch_op.drop_column('sociolinguistic_score')
        batch_op.drop_column('pragmatic_feedback')
        batch_op.drop_column('pragmatic_score')
        batch_op.drop_column('sociolinguistic_feedback')
        batch_op.drop_column('linguistic_feedback')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('written_expression_ai_corrections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linguistic_feedback', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sociolinguistic_feedback', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pragmatic_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pragmatic_feedback', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sociolinguistic_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('linguistic_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('task_feedback')
        batch_op.drop_column('task_score')
        batch_op.drop_column('grammar_feedback')
        batch_op.drop_column('grammar_score')
        batch_op.drop_column('vocabulary_feedback')
        batch_op.drop_column('vocabulary_score')
        batch_op.drop_column('cohesion_feedback')
        batch_op.drop_column('cohesion_score')
        batch_op.drop_column('structure_feedback')
        batch_op.drop_column('structure_score')

    # ### end Alembic commands ###