"""add series and questions models

Revision ID: 033cef4e2369
Revises: 81ca93297f68
Create Date: 2025-12-22 04:20:55.560262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033cef4e2369'
down_revision = '81ca93297f68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###