"""Agent IA pour EO

Revision ID: 6f3a709e51f8
Revises: cafb725c51fa
Create Date: 2026-07-14 08:49:22.998017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3a709e51f8'
down_revision = 'cafb725c51fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###