"""add unique constraint comprehension_result

Revision ID: 5b9e3fb7226f
Revises: 46a415857e79
Create Date: 2026-01-09 06:09:50.325804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9e3fb7226f'
down_revision = '46a415857e79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprehension_results', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_comprehension_result_attempt_type', ['attempt_id', 'type'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprehension_results', schema=None) as batch_op:
        batch_op.drop_constraint('uq_comprehension_result_attempt_type', type_='unique')

    # ### end Alembic commands ###