"""Ajout du module pour les expression ouverte au public

Revision ID: 8390e3db0c2e
Revises: af9f49212893
Create Date: 2026-03-17 00:23:44.806128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8390e3db0c2e'
down_revision = 'af9f49212893'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_sessions',
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_sessions_month'), ['month'], unique=True)

    op.create_table('ee_combinations',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('task1_instruction', sa.Text(), nullable=False),
    sa.Column('task1_word_min', sa.Integer(), nullable=False),
    sa.Column('task1_word_max', sa.Integer(), nullable=False),
    sa.Column('task2_instruction', sa.Text(), nullable=False),
    sa.Column('task2_word_min', sa.Integer(), nullable=False),
    sa.Column('task2_word_max', sa.Integer(), nullable=False),
    sa.Column('task3_title', sa.String(length=500), nullable=False),
    sa.Column('task3_document_1', sa.Text(), nullable=False),
    sa.Column('task3_document_2', sa.Text(), nullable=False),
    sa.Column('task3_word_min', sa.Integer(), nullable=False),
    sa.Column('task3_word_max', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['monthly_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ee_combinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ee_combinations_session_id'), ['session_id'], unique=False)

    op.create_table('eo_task2_pool',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['monthly_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eo_task2_pool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eo_task2_pool_session_id'), ['session_id'], unique=False)

    op.create_table('eo_task3_pool',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['monthly_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eo_task3_pool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eo_task3_pool_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_task3_pool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eo_task3_pool_session_id'))

    op.drop_table('eo_task3_pool')
    with op.batch_alter_table('eo_task2_pool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eo_task2_pool_session_id'))

    op.drop_table('eo_task2_pool')
    with op.batch_alter_table('ee_combinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ee_combinations_session_id'))

    op.drop_table('ee_combinations')
    with op.batch_alter_table('monthly_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_sessions_month'))

    op.drop_table('monthly_sessions')
    # ### end Alembic commands ###