"""Update public expression

Revision ID: cafb725c51fa
Revises: af0c4fe560f1
Create Date: 2026-05-22 01:41:49.414746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafb725c51fa'
down_revision = 'af0c4fe560f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ee_combinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task1_correction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('task2_correction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('task3_correction', sa.Text(), nullable=True))

    with op.batch_alter_table('eo_task2_pool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eo_task2_correction', sa.Text(), nullable=True))

    with op.batch_alter_table('eo_task3_pool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eo_task3_correction', sa.Text(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('amount_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('commission_due',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('commission_due',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
        batch_op.alter_column('amount_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
        batch_op.alter_column('discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)

    with op.batch_alter_table('eo_task3_pool', schema=None) as batch_op:
        batch_op.drop_column('eo_task3_correction')

    with op.batch_alter_table('eo_task2_pool', schema=None) as batch_op:
        batch_op.drop_column('eo_task2_correction')

    with op.batch_alter_table('ee_combinations', schema=None) as batch_op:
        batch_op.drop_column('task3_correction')
        batch_op.drop_column('task2_correction')
        batch_op.drop_column('task1_correction')

    # ### end Alembic commands ###