"""add trial subscription and update is_active default

Revision ID: af9f49212893
Revises: dc8432034e65
Create Date: 2026-01-26 17:31:29.106592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9f49212893'
down_revision = 'dc8432034e65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###