"""Agent IA pour EO V3

Revision ID: 74be25a61c6e
Revises: c3df657bd58b
Create Date: 2026-07-15 02:23:40.778697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74be25a61c6e'
down_revision = 'c3df657bd58b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('written_expression_simulator_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('task1_instruction', sa.String(), nullable=False),
    sa.Column('task1_content', sa.String(), nullable=False),
    sa.Column('task2_instruction', sa.String(), nullable=False),
    sa.Column('task2_content', sa.String(), nullable=False),
    sa.Column('task3_instruction', sa.String(), nullable=False),
    sa.Column('task3_content', sa.String(), nullable=False),
    sa.Column('structure_score', sa.Float(), nullable=False),
    sa.Column('structure_feedback', sa.String(), nullable=False),
    sa.Column('cohesion_score', sa.Float(), nullable=False),
    sa.Column('cohesion_feedback', sa.String(), nullable=False),
    sa.Column('vocabulary_score', sa.Float(), nullable=False),
    sa.Column('vocabulary_feedback', sa.String(), nullable=False),
    sa.Column('grammar_score', sa.Float(), nullable=False),
    sa.Column('grammar_feedback', sa.String(), nullable=False),
    sa.Column('task_score', sa.Float(), nullable=False),
    sa.Column('task_feedback', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('cecrl_level', sa.String(length=10), nullable=False),
    sa.Column('appreciation', sa.String(), nullable=False),
    sa.Column('task_feedbacks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('corrections_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggestions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('written_expression_simulator_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_written_expression_simulator_attempts_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_written_expression_simulator_attempts_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('written_expression_simulator_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_written_expression_simulator_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_written_expression_simulator_attempts_series_id'))

    op.drop_table('written_expression_simulator_attempts')
    # ### end Alembic commands ###