"""add_title_and_documents_to_expression_tasks

Revision ID: a7a3b8ec7341
Revises: 90debe1792d3
Create Date: 2026-01-02 05:14:23.409088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a3b8ec7341'
down_revision = '90debe1792d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expression_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('document_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('document_2', sa.Text(), nullable=True))
        batch_op.alter_column('instruction_text',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expression_tasks', schema=None) as batch_op:
        batch_op.alter_column('instruction_text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('document_2')
        batch_op.drop_column('document_1')
        batch_op.drop_column('title')

    # ### end Alembic commands ###