"""Agent IA pour EO V2

Revision ID: c3df657bd58b
Revises: 6f3a709e51f8
Create Date: 2026-07-14 10:02:06.664924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3df657bd58b'
down_revision = '6f3a709e51f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expression_orale_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.Column('spoken_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('capped', sa.Boolean(), nullable=False),
    sa.Column('cap_reason', sa.String(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('improvement_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('live_provider_used', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['expression_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expression_orale_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expression_orale_attempts_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expression_orale_attempts_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expression_orale_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expression_orale_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_expression_orale_attempts_series_id'))

    op.drop_table('expression_orale_attempts')
    # ### end Alembic commands ###