"""ambassador sales tracking remittances and contracts

Revision ID: f38a3bd16f13
Revises: ae4f4a91a1b2
Create Date: 2026-10-06 02:45:38.775889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38a3bd16f13'
down_revision = 'ae4f4a91a1b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambassador_contracts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('statut', sa.Enum('brouillon', 'signe', 'resilie', name='statut_contrat_ambassadeur', native_enum=False), nullable=False),
    sa.Column('nom_complet', sa.String(length=150), nullable=False),
    sa.Column('telephone', sa.String(length=40), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=False),
    sa.Column('piece_identite', sa.String(length=60), nullable=False),
    sa.Column('taux_commission', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('delai_reversement_heures', sa.Integer(), nullable=False),
    sa.Column('numero_mobile_money_reception', sa.String(length=40), nullable=True),
    sa.Column('duree_mois', sa.Integer(), nullable=False),
    sa.Column('preavis_resiliation_jours', sa.Integer(), nullable=False),
    sa.Column('ville_juridiction', sa.String(length=100), nullable=False),
    sa.Column('date_signature', sa.Date(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cree_par_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cree_par_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ambassador_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ambassador_contracts_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_ambassador_contracts_user_id'), ['user_id'], unique=False)

    op.create_table('ambassador_remittances',
    sa.Column('ambassador_user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ambassador_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ambassador_remittances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ambassador_remittances_ambassador_user_id'), ['ambassador_user_id'], unique=False)

    with op.batch_alter_table('referral_earnings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_amount', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('plan_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('collected_by_ambassador', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###

    # ── Remplissage des gains existants ──────────────────────────
    # Prix réellement payé par le client
    op.execute("""
        UPDATE referral_earnings re
        SET sale_amount = ROUND(p.amount_paid)::int
        FROM payments p
        WHERE p.id = re.payment_id
    """)

    # Forfait vendu
    op.execute("""
        UPDATE referral_earnings re
        SET plan_name = pl.name
        FROM payments p
        JOIN subscriptions s ON s.id = p.subscription_id
        JOIN plans pl ON pl.id = s.plan_id
        WHERE p.id = re.payment_id
    """)

    # Ventes antérieures au système de contrats : laissées hors du suivi
    # des reversements (aucune dette créée). Décommenter pour les
    # compter comme ventes encaissées par l'ambassadeur.
    # op.execute("""
    #     UPDATE referral_earnings re
    #     SET collected_by_ambassador = true
    #     FROM payments p
    #     WHERE p.id = re.payment_id
    #       AND p.transaction_reference LIKE 'AMB-%'
    # """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_earnings', schema=None) as batch_op:
        batch_op.drop_column('collected_by_ambassador')
        batch_op.drop_column('plan_name')
        batch_op.drop_column('sale_amount')

    with op.batch_alter_table('ambassador_remittances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambassador_remittances_ambassador_user_id'))

    op.drop_table('ambassador_remittances')
    with op.batch_alter_table('ambassador_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambassador_contracts_user_id'))
        batch_op.drop_index(batch_op.f('ix_ambassador_contracts_numero'))

    op.drop_table('ambassador_contracts')
    # ### end Alembic commands ###