"""ajout is_trial dans subscription

Revision ID: bbe83605b44e
Revises: 8390e3db0c2e
Create Date: 2026-05-03 12:40:11.577685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe83605b44e'
down_revision = '8390e3db0c2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###