"""update question model and add asked_question column

Revision ID: dc8432034e65
Revises: 32eeb8672594
Create Date: 2026-01-25 15:58:16.729867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8432034e65'
down_revision = '32eeb8672594'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_credit_purchases', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('ai_credit_purchases_payment_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_ai_credit_purchases_payment_id'))
        batch_op.create_index(batch_op.f('ix_ai_credit_purchases_payment_id'), ['payment_id'], unique=True)

    with op.batch_alter_table('comprehension_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asked_question', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprehension_questions', schema=None) as batch_op:
        batch_op.drop_column('asked_question')

    with op.batch_alter_table('ai_credit_purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_credit_purchases_payment_id'))
        batch_op.create_index(batch_op.f('idx_ai_credit_purchases_payment_id'), ['payment_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('ai_credit_purchases_payment_id_key'), ['payment_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)

    # ### end Alembic commands ###