"""add partners table

Revision ID: 6004b0543c73
Revises: 81ca93297f68
Create Date: 2026-05-23 11:15:57.452464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6004b0543c73'
down_revision = '81ca93297f68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_email')
    )
    op.create_table('promo_codes',
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=10), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("discount_type != 'percent' OR discount_value <= 100", name='ck_promo_percent_max_100'),
    sa.CheckConstraint('commission_rate >= 0 AND commission_rate <= 100', name='ck_promo_commission_range'),
    sa.CheckConstraint('discount_value > 0', name='ck_promo_discount_positive'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_promo_codes_partner_id'), ['partner_id'], unique=False)

    with op.batch_alter_table('ee_combinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task1_correction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('task2_correction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('task3_correction', sa.Text(), nullable=True))

    with op.batch_alter_table('eo_task2_pool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eo_task2_correction', sa.Text(), nullable=True))

    with op.batch_alter_table('eo_task3_pool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eo_task3_correction', sa.Text(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo_code_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('commission_due', sa.Float(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_payments_promo_code_id'), ['promo_code_id'], unique=False)
        batch_op.create_foreign_key(None, 'promo_codes', ['promo_code_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_promo_code_id'))
        batch_op.drop_column('commission_due')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('promo_code_id')

    with op.batch_alter_table('eo_task3_pool', schema=None) as batch_op:
        batch_op.drop_column('eo_task3_correction')

    with op.batch_alter_table('eo_task2_pool', schema=None) as batch_op:
        batch_op.drop_column('eo_task2_correction')

    with op.batch_alter_table('ee_combinations', schema=None) as batch_op:
        batch_op.drop_column('task3_correction')
        batch_op.drop_column('task2_correction')
        batch_op.drop_column('task1_correction')

    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_codes_partner_id'))
        batch_op.drop_index(batch_op.f('ix_promo_codes_code'))

    op.drop_table('promo_codes')
    op.drop_table('partners')
    # ### end Alembic commands ###
