"""add pawapay fields to payments

Revision ID: d4070d8e3233
Revises: 74be25a61c6e
Create Date: 2026-07-22 00:05:45.977725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4070d8e3233'
down_revision = '74be25a61c6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pawapay_deposit_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('webhook_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('validated_manually_by', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_pawapay_deposit_id'), ['pawapay_deposit_id'], unique=False)
        batch_op.create_unique_constraint('uq_payment_pawapay_deposit_id', ['pawapay_deposit_id'])
        batch_op.create_foreign_key(None, 'users', ['validated_manually_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_ambassador',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false'),
            )
        )
        batch_op.add_column(sa.Column('referred_by_user_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_is_ambassador'), ['is_ambassador'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_referred_by_user_id'), ['referred_by_user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['referred_by_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_referred_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_is_ambassador'))
        batch_op.drop_column('referred_by_user_id')
        batch_op.drop_column('is_ambassador')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_payment_pawapay_deposit_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_payments_pawapay_deposit_id'))
        batch_op.drop_column('validated_manually_by')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('webhook_payload')
        batch_op.drop_column('pawapay_deposit_id')
        batch_op.drop_column('operator')

    # ### end Alembic commands ###