"""add_description_and_features_to_plans

Revision ID: 46a415857e79
Revises: a7a3b8ec7341
Create Date: 2026-01-02 16:02:05.377543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a415857e79'
down_revision = 'a7a3b8ec7341'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('features', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('features')
        batch_op.drop_column('description')

    # ### end Alembic commands ###