"""user weekly goal days

Revision ID: 0ea40260658b
Revises: f38a3bd16f13
Create Date: 2026-10-06 06:01:58.233968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea40260658b'
down_revision = 'f38a3bd16f13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_goal_days', sa.Integer(), server_default='4', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('weekly_goal_days')

    # ### end Alembic commands ###